openapi: "3.0.0"
info:
  title: "API de Transactions"
  description: "Documentation de l'API pour gérer les transactions des utilisateurs."
  version: "1.0.0"
servers:
  - url: "http://api.example.com/v1"
    description: "Serveur principal (Production)"
  - url: "http://staging.api.example.com/v1"
    description: "Serveur de test (Staging)"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
          description: "ID unique de la transaction."
        accountId:
          type: string
          description: "ID du compte associé à la transaction."
        userId:
          type: string
          description: "ID de l'utilisateur ayant effectué la transaction."
        date:
          type: string
          format: date
          description: "Date de la transaction."
        description:
          type: string
          description: "Description de la transaction."
        amount:
          type: number
          format: float
          description: "Montant de la transaction."
        balance:
          type: number
          format: float
          description: "Solde après la transaction."
      example:
        accountId: "number"
        userId: "number"
        date: "date"
        description: "string"
        amount: number
        balance: number
    NewTransaction:
      type: object
      required:
        - accountId
        - userId
        - date
        - description
        - amount
        - balance
      properties:
        accountId:
          type: string
          description: "ID du compte associé à la transaction."
        userId:
          type: string
          description: "ID de l'utilisateur ayant effectué la transaction."
        date:
          type: string
          format: date
          description: "Date de la transaction."
        description:
          type: string
          description: "Description de la transaction."
        amount:
          type: number
          format: float
          description: "Montant de la transaction."
        balance:
          type: number
          format: float
          description: "Solde après la transaction."
      example:
        accountId: "number"
        userId: "number"
        date: "date"
        description: "string"
        amount: number
        balance: number
    UpdateTransaction:
      type: object
      properties:
        transactionId:
          type: string
          description: "ID unique de la transaction."
        date:
          type: string
          format: date
          description: "Date de la transaction."
        description:
          type: string
          description: "Description de la transaction."
        amount:
          type: number
          format: float
          description: "Montant de la transaction."
        balance:
          type: number
          format: float
          description: "Solde après la transaction."
      example:
        transactionId: "string"
        date: "date"
        description: "string"
        amount: number
        balance: number
    TransactionsGroupedByAccount:
      type: object
      properties:
        accountId:
          type: string
          description: "ID du compte."
        transactions:
          type: array
          items:
            $ref: "#/components/schemas/Transaction"
      example:
        accountId: "number"
        transactions:
          - id: "string"
            accountId: "number"
            userId: "number"
            date: "date"
            description: "string"
            amount: number
            balance: number
security:
  - BearerAuth: []
paths:
  /transactions:
    post:
      summary: "Crée une nouvelle transaction"
      description: "Ajoute une nouvelle transaction à la base de données."
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewTransaction"
      responses:
        "201":
          description: "Transaction créée avec succès."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "400":
          description: "Requête invalide."
        "500":
          description: "Erreur interne du serveur."
  /transactions/{transactionId}:
    put:
      summary: "Met à jour une transaction spécifique"
      description: "Met à jour les détails d'une transaction existante."
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTransaction"
      responses:
        "200":
          description: "Transaction mise à jour avec succès."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "400":
          description: "Requête invalide."
        "404":
          description: "Transaction non trouvée."
        "500":
          description: "Erreur interne du serveur."
    delete:
      summary: "Supprime une transaction spécifique"
      description: "Supprime une transaction existante en utilisant son ID."
      security:
        - BearerAuth: []
      parameters:
        - name: transactionId
          in: path
          required: true
          description: "ID de la transaction à supprimer."
          schema:
            type: string
      responses:
        "204":
          description: "Transaction supprimée avec succès."
        "404":
          description: "Transaction non trouvée."
        "500":
          description: "Erreur interne du serveur."
  /transactions/user/{userId}:
    get:
      summary: "Récupère les transactions d'un utilisateur regroupées par compte"
      description: "Retourne toutes les transactions associées à un utilisateur, regroupées par compte."
      security:
        - BearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          description: "ID de l'utilisateur dont les transactions doivent être récupérées."
          schema:
            type: string
      responses:
        "200":
          description: "Liste des transactions de l'utilisateur regroupée par compte récupérée avec succès."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TransactionsGroupedByAccount"
        "404":
          description: "Utilisateur non trouvé."
        "500":
          description: "Erreur interne du serveur."
